[package]
name = "ticker-rs"
version = "0.1.0"
authors = ["rektdeckard <friedtm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport="4.0.0"
sysinfo="0.15.8"
# periodic="0.1.1"
